# GitHub Sponsors and other funding platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [quinnjr]
# patreon: username
# open_collective: armature
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ['https://www.example.com', 'https://www.example.com']


