name: Bug Report
description: File a bug report to help us improve Armature
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - quinnjr

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new project with '...'
        2. Add this code '....'
        3. Run the application '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal reproducible code sample
      render: rust
      placeholder: |
        use armature::prelude::*;

        // Your code here
    validations:
      required: false

  - type: input
    id: armature-version
    attributes:
      label: Armature Version
      description: Which version of Armature are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What is your Rust version? (Run `rustc --version`)
      placeholder: "rustc 1.85.0 (2024-12-05)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.)
      placeholder: |
        - Error logs
        - Stack trace
        - Screenshots
        - Related issues
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to submit a PR if guidance is provided
          required: false
