name: Feature Request
description: Suggest a new feature or enhancement for Armature
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - quinnjr

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input in making Armature better.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Module/Crate
        - Enhancement to Existing Feature
        - API Improvement
        - Performance Improvement
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like to see...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: If applicable, provide example code showing how the feature would be used
      render: rust
      placeholder: |
        use armature::prelude::*;

        // Example of how the feature would work
        #[controller("/api")]
        struct MyController {
            // Your example here
        }
    validations:
      required: false

  - type: dropdown
    id: comparison
    attributes:
      label: Comparison to Other Frameworks
      description: Does NestJS, Express, Actix-web, Rocket, or Axum have this feature?
      options:
        - "Yes - NestJS has this"
        - "Yes - Express/Koa has this"
        - "Yes - Actix-web has this"
        - "Yes - Rocket has this"
        - "Yes - Axum has this"
        - "No - This is novel"
        - "Not Applicable"
    validations:
      required: false

  - type: textarea
    id: reference
    attributes:
      label: Reference Implementation
      description: If another framework has this, provide links or examples
      placeholder: |
        NestJS: https://docs.nestjs.com/...
        Actix-web: https://actix.rs/...
    validations:
      required: false

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change to the API?
      options:
        - "No - Fully backward compatible"
        - "Yes - Minor breaking change"
        - "Yes - Major breaking change"
        - "Unknown"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my project"
        - "High - Would significantly improve my workflow"
        - "Medium - Nice to have"
        - "Low - Just a suggestion"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I am willing to submit a PR to implement this feature if guidance is provided
          required: false
